import Dexie, { type Table } from 'dexie';
import { InventoryItem, Order, PricingRule, BrokerAccount } from '../types';

export class TicketBrokerDB extends Dexie {
  inventory!: Table<InventoryItem, number>;
  orders!: Table<Order, number>;
  pricingRules!: Table<PricingRule, number>;
  brokerAccount!: Table<BrokerAccount, number>;

  constructor() {
    super('TicketBroker_DB');

    this.version(1).stores({
      inventory: '++id, eventName, category, eventDate, venue, section, row, status, specListing',
      orders: '++id, inventoryId, orderNumber, marketplace, orderDate, fulfillmentStatus',
      pricingRules: '++id, name, isActive',
      brokerAccount: '++id, email',
    });
  }
}

export const db = new TicketBrokerDB();

export const INITIAL_INVENTORY_SEED: Omit<InventoryItem, 'id'>[] = [
  // CONCERTS (7 listings)
  {
    eventName: 'Taylor Swift - The Eras Tour',
    category: 'Concert',
    eventDate: '2026-10-18T19:00:00.000Z',
    venue: 'Hard Rock Stadium',
    city: 'Miami, FL',
    section: 'A4',
    row: '12',
    seatStart: '5',
    seatEnd: '8',
    quantity: 4,
    costPerTicket: 650.00,
    totalCost: 2600.00,
    faceValue: 499.00,
    listPrice: 1450.00,
    marketFloorPrice: 1400.00,
    cardReference: 'Amex Platinum #4821',
    specListing: false,
    status: 'Available',
    channels: { stubhub: true, vividseats: true, seatgeek: true, ticketmaster: true },
    barcodes: ['TS-MIA-A4-12-05', 'TS-MIA-A4-12-06', 'TS-MIA-A4-12-07', 'TS-MIA-A4-12-08'],
    lastRepricedAt: new Date().toISOString(),
  },
  {
    eventName: 'Drake & 21 Savage - It\'s All A Blur Tour',
    category: 'Concert',
    eventDate: '2026-09-12T20:00:00.000Z',
    venue: 'Madison Square Garden',
    city: 'New York, NY',
    section: '118',
    row: '4',
    seatStart: '1',
    seatEnd: '2',
    quantity: 2,
    costPerTicket: 320.00,
    totalCost: 640.00,
    faceValue: 280.00,
    listPrice: 620.00,
    marketFloorPrice: 600.00,
    cardReference: 'Chase Sapphire #0092',
    specListing: false,
    status: 'Sold',
    channels: { stubhub: true, vividseats: false, seatgeek: true, ticketmaster: false },
    barcodes: ['DRK-MSG-118-4-1', 'DRK-MSG-118-4-2'],
    lastRepricedAt: new Date().toISOString(),
  },
  {
    eventName: 'Beyoncé - Renaissance World Tour',
    category: 'Concert',
    eventDate: '2026-11-05T19:30:00.000Z',
    venue: 'SoFi Stadium',
    city: 'Los Angeles, CA',
    section: 'B2',
    row: '8',
    seatStart: '15',
    seatEnd: '18',
    quantity: 4,
    costPerTicket: 550.00,
    totalCost: 2200.00,
    faceValue: 450.00,
    listPrice: 1100.00,
    marketFloorPrice: 1080.00,
    cardReference: 'Amex Business #9912',
    specListing: true,
    targetDeliveryDate: '2026-11-01T00:00:00.000Z',
    status: 'Available',
    channels: { stubhub: true, vividseats: true, seatgeek: true, ticketmaster: true },
    barcodes: [],
    lastRepricedAt: new Date().toISOString(),
  },
  {
    eventName: 'Coldplay - Music of the Spheres Tour',
    category: 'Concert',
    eventDate: '2026-09-02T19:00:00.000Z', // < 48 hours away for time decay test
    venue: 'Rose Bowl',
    city: 'Pasadena, CA',
    section: '12-H',
    row: '15',
    seatStart: '101',
    seatEnd: '104',
    quantity: 4,
    costPerTicket: 210.00,
    totalCost: 840.00,
    faceValue: 180.00,
    listPrice: 480.00,
    marketFloorPrice: 420.00,
    cardReference: 'Capital One Spark #7714',
    specListing: false,
    status: 'Available',
    channels: { stubhub: true, vividseats: true, seatgeek: false, ticketmaster: true },
    barcodes: ['CP-RB-12H-101', 'CP-RB-12H-102', 'CP-RB-12H-103', 'CP-RB-12H-104'],
    lastRepricedAt: new Date().toISOString(),
  },
  {
    eventName: 'Zach Bryan - The Quittin Time Tour',
    category: 'Concert',
    eventDate: '2026-10-02T20:00:00.000Z',
    venue: 'Red Rocks Amphitheatre',
    city: 'Morrison, CO',
    section: 'Reserved 2',
    row: '22',
    seatStart: '44',
    seatEnd: '47',
    quantity: 4,
    costPerTicket: 290.00,
    totalCost: 1160.00,
    faceValue: 220.00,
    listPrice: 590.00,
    marketFloorPrice: 570.00,
    cardReference: 'Chase Ink #3310',
    specListing: false,
    status: 'Available',
    channels: { stubhub: true, vividseats: true, seatgeek: true, ticketmaster: false },
    barcodes: ['ZB-RR-R2-44', 'ZB-RR-R2-45', 'ZB-RR-R2-46', 'ZB-RR-R2-47'],
    lastRepricedAt: new Date().toISOString(),
  },
  {
    eventName: 'Billie Eilish - Hit Me Hard and Soft Tour',
    category: 'Concert',
    eventDate: '2026-11-20T19:30:00.000Z',
    venue: 'United Center',
    city: 'Chicago, IL',
    section: '112',
    row: '6',
    seatStart: '7',
    seatEnd: '10',
    quantity: 4,
    costPerTicket: 240.00,
    totalCost: 960.00,
    faceValue: 195.00,
    listPrice: 530.00,
    marketFloorPrice: 510.00,
    cardReference: 'Citi DoubleCash #8801',
    specListing: true,
    targetDeliveryDate: '2026-11-15T00:00:00.000Z',
    status: 'Available',
    channels: { stubhub: true, vividseats: true, seatgeek: true, ticketmaster: true },
    barcodes: [],
    lastRepricedAt: new Date().toISOString(),
  },
  {
    eventName: 'Bruno Mars - Live in Las Vegas',
    category: 'Concert',
    eventDate: '2026-09-30T21:00:00.000Z',
    venue: 'Dolby Live at Park MGM',
    city: 'Las Vegas, NV',
    section: '202',
    row: 'C',
    seatStart: '12',
    seatEnd: '13',
    quantity: 2,
    costPerTicket: 410.00,
    totalCost: 820.00,
    faceValue: 350.00,
    listPrice: 890.00,
    marketFloorPrice: 870.00,
    cardReference: 'Amex Platinum #4821',
    specListing: false,
    status: 'Available',
    channels: { stubhub: true, vividseats: false, seatgeek: true, ticketmaster: true },
    barcodes: ['BM-MGM-202-C12', 'BM-MGM-202-C13'],
    lastRepricedAt: new Date().toISOString(),
  },

  // SPORTS (7 listings)
  {
    eventName: 'Super Bowl LVIII',
    category: 'Sports',
    eventDate: '2027-02-14T17:30:00.000Z',
    venue: 'Allegiant Stadium',
    city: 'Las Vegas, NV',
    section: '142',
    row: '18',
    seatStart: '1',
    seatEnd: '2',
    quantity: 2,
    costPerTicket: 3200.00,
    totalCost: 6400.00,
    faceValue: 2500.00,
    listPrice: 7800.00,
    marketFloorPrice: 7600.00,
    cardReference: 'Amex Centurion #0001',
    specListing: true,
    targetDeliveryDate: '2027-02-10T00:00:00.000Z',
    status: 'Available',
    channels: { stubhub: true, vividseats: true, seatgeek: true, ticketmaster: true },
    barcodes: [],
    lastRepricedAt: new Date().toISOString(),
  },
  {
    eventName: 'NBA Finals Game 7',
    category: 'Sports',
    eventDate: '2026-09-01T20:00:00.000Z', // Today/Tomorrow - triggering urgent fulfillment
    venue: 'TD Garden',
    city: 'Boston, MA',
    section: 'Loge 1',
    row: '10',
    seatStart: '3',
    seatEnd: '4',
    quantity: 2,
    costPerTicket: 1100.00,
    totalCost: 2200.00,
    faceValue: 850.00,
    listPrice: 2450.00,
    marketFloorPrice: 2400.00,
    cardReference: 'Chase Sapphire #0092',
    specListing: false,
    status: 'Sold',
    channels: { stubhub: true, vividseats: true, seatgeek: true, ticketmaster: true },
    barcodes: [],
    lastRepricedAt: new Date().toISOString(),
  },
  {
    eventName: 'El Clásico: Real Madrid vs Barcelona',
    category: 'Sports',
    eventDate: '2026-10-25T20:00:00.000Z',
    venue: 'MetLife Stadium',
    city: 'East Rutherford, NJ',
    section: '111A',
    row: '7',
    seatStart: '9',
    seatEnd: '12',
    quantity: 4,
    costPerTicket: 480.00,
    totalCost: 1920.00,
    faceValue: 390.00,
    listPrice: 980.00,
    marketFloorPrice: 950.00,
    cardReference: 'Amex Platinum #4821',
    specListing: false,
    status: 'Available',
    channels: { stubhub: true, vividseats: true, seatgeek: false, ticketmaster: true },
    barcodes: ['EC-ML-111A-09', 'EC-ML-111A-10', 'EC-ML-111A-11', 'EC-ML-111A-12'],
    lastRepricedAt: new Date().toISOString(),
  },
  {
    eventName: 'New York Yankees vs Boston Red Sox',
    category: 'Sports',
    eventDate: '2026-09-15T19:05:00.000Z',
    venue: 'Yankee Stadium',
    city: 'Bronx, NY',
    section: 'Main 214',
    row: '3',
    seatStart: '1',
    seatEnd: '4',
    quantity: 4,
    costPerTicket: 135.00,
    totalCost: 540.00,
    faceValue: 110.00,
    listPrice: 290.00,
    marketFloorPrice: 280.00,
    cardReference: 'Citi DoubleCash #8801',
    specListing: false,
    status: 'Sold',
    channels: { stubhub: true, vividseats: true, seatgeek: true, ticketmaster: true },
    barcodes: ['NYY-BOS-214-1', 'NYY-BOS-214-2', 'NYY-BOS-214-3', 'NYY-BOS-214-4'],
    lastRepricedAt: new Date().toISOString(),
  },
  {
    eventName: 'Kansas City Chiefs vs Buffalo Bills',
    category: 'Sports',
    eventDate: '2026-11-15T16:25:00.000Z',
    venue: 'GEHA Field at Arrowhead Stadium',
    city: 'Kansas City, MO',
    section: '119',
    row: '14',
    seatStart: '11',
    seatEnd: '14',
    quantity: 4,
    costPerTicket: 340.00,
    totalCost: 1360.00,
    faceValue: 275.00,
    listPrice: 790.00,
    marketFloorPrice: 750.00,
    cardReference: 'Chase Ink #3310',
    specListing: false,
    status: 'Available',
    channels: { stubhub: true, vividseats: true, seatgeek: true, ticketmaster: true },
    barcodes: ['KCC-BUF-119-11', 'KCC-BUF-119-12', 'KCC-BUF-119-13', 'KCC-BUF-119-14'],
    lastRepricedAt: new Date().toISOString(),
  },
  {
    eventName: 'UFC 308: World Championship Fight',
    category: 'Sports',
    eventDate: '2026-10-10T22:00:00.000Z',
    venue: 'T-Mobile Arena',
    city: 'Las Vegas, NV',
    section: 'Floor 4',
    row: 'B',
    seatStart: '5',
    seatEnd: '6',
    quantity: 2,
    costPerTicket: 1250.00,
    totalCost: 2500.00,
    faceValue: 990.00,
    listPrice: 2850.00,
    marketFloorPrice: 2800.00,
    cardReference: 'Amex Centurion #0001',
    specListing: false,
    status: 'Available',
    channels: { stubhub: true, vividseats: true, seatgeek: true, ticketmaster: false },
    barcodes: ['UFC308-FL4-B5', 'UFC308-FL4-B6'],
    lastRepricedAt: new Date().toISOString(),
  },
  {
    eventName: 'US Open Tennis: Men\'s Final',
    category: 'Sports',
    eventDate: '2026-09-08T16:00:00.000Z',
    venue: 'Arthur Ashe Stadium',
    city: 'Flushing, NY',
    section: 'Courtside Box 52',
    row: 'A',
    seatStart: '1',
    seatEnd: '2',
    quantity: 2,
    costPerTicket: 1800.00,
    totalCost: 3600.00,
    faceValue: 1400.00,
    listPrice: 3900.00,
    marketFloorPrice: 3850.00,
    cardReference: 'Capital One Spark #7714',
    specListing: false,
    status: 'Available',
    channels: { stubhub: true, vividseats: true, seatgeek: true, ticketmaster: true },
    barcodes: ['USO-AA-CB52-A1', 'USO-AA-CB52-A2'],
    lastRepricedAt: new Date().toISOString(),
  },

  // THEATER (6 listings)
  {
    eventName: 'Hamilton',
    category: 'Theater',
    eventDate: '2026-09-24T19:00:00.000Z',
    venue: 'Richard Rodgers Theatre',
    city: 'New York, NY',
    section: 'Orchestra Center',
    row: 'EE',
    seatStart: '101',
    seatEnd: '102',
    quantity: 2,
    costPerTicket: 275.00,
    totalCost: 550.00,
    faceValue: 220.00,
    listPrice: 580.00,
    marketFloorPrice: 560.00,
    cardReference: 'Amex Business #9912',
    specListing: false,
    status: 'Available',
    channels: { stubhub: true, vividseats: true, seatgeek: true, ticketmaster: true },
    barcodes: ['HAM-RR-ORCH-101', 'HAM-RR-ORCH-102'],
    lastRepricedAt: new Date().toISOString(),
  },
  {
    eventName: 'Wicked',
    category: 'Theater',
    eventDate: '2026-10-12T19:30:00.000Z',
    venue: 'Gershwin Theatre',
    city: 'New York, NY',
    section: 'Front Mezzanine',
    row: 'B',
    seatStart: '12',
    seatEnd: '15',
    quantity: 4,
    costPerTicket: 190.00,
    totalCost: 760.00,
    faceValue: 150.00,
    listPrice: 380.00,
    marketFloorPrice: 360.00,
    cardReference: 'Chase Sapphire #0092',
    specListing: false,
    status: 'Available',
    channels: { stubhub: true, vividseats: false, seatgeek: true, ticketmaster: true },
    barcodes: ['WCK-GER-FM-B12', 'WCK-GER-FM-B13', 'WCK-GER-FM-B14', 'WCK-GER-FM-B15'],
    lastRepricedAt: new Date().toISOString(),
  },
  {
    eventName: 'The Lion King',
    category: 'Theater',
    eventDate: '2026-10-04T14:00:00.000Z',
    venue: 'Minskoff Theatre',
    city: 'New York, NY',
    section: 'Orchestra Prime',
    row: 'K',
    seatStart: '18',
    seatEnd: '21',
    quantity: 4,
    costPerTicket: 220.00,
    totalCost: 880.00,
    faceValue: 185.00,
    listPrice: 460.00,
    marketFloorPrice: 440.00,
    cardReference: 'Citi DoubleCash #8801',
    specListing: false,
    status: 'Available',
    channels: { stubhub: true, vividseats: true, seatgeek: true, ticketmaster: true },
    barcodes: ['LK-MIN-ORCH-K18', 'LK-MIN-ORCH-K19', 'LK-MIN-ORCH-K20', 'LK-MIN-ORCH-K21'],
    lastRepricedAt: new Date().toISOString(),
  },
  {
    eventName: 'Harry Potter and the Cursed Child',
    category: 'Theater',
    eventDate: '2026-11-14T19:00:00.000Z',
    venue: 'Lyric Theatre',
    city: 'New York, NY',
    section: 'Dress Circle',
    row: 'D',
    seatStart: '7',
    seatEnd: '8',
    quantity: 2,
    costPerTicket: 165.00,
    totalCost: 330.00,
    faceValue: 130.00,
    listPrice: 340.00,
    marketFloorPrice: 320.00,
    cardReference: 'Capital One Spark #7714',
    specListing: true,
    targetDeliveryDate: '2026-11-10T00:00:00.000Z',
    status: 'Available',
    channels: { stubhub: true, vividseats: true, seatgeek: false, ticketmaster: true },
    barcodes: [],
    lastRepricedAt: new Date().toISOString(),
  },
  {
    eventName: 'Les Misérables - US Tour',
    category: 'Theater',
    eventDate: '2026-09-28T20:00:00.000Z',
    venue: 'Kennedy Center Opera House',
    city: 'Washington, DC',
    section: 'Tier 1 Box',
    row: 'A',
    seatStart: '1',
    seatEnd: '4',
    quantity: 4,
    costPerTicket: 185.00,
    totalCost: 740.00,
    faceValue: 155.00,
    listPrice: 395.00,
    marketFloorPrice: 380.00,
    cardReference: 'Amex Platinum #4821',
    specListing: false,
    status: 'Sold',
    channels: { stubhub: true, vividseats: true, seatgeek: true, ticketmaster: false },
    barcodes: ['LM-KC-T1-A1', 'LM-KC-T1-A2', 'LM-KC-T1-A3', 'LM-KC-T1-A4'],
    lastRepricedAt: new Date().toISOString(),
  },
  {
    eventName: 'The Phantom of the Opera',
    category: 'Theater',
    eventDate: '2026-12-05T20:00:00.000Z',
    venue: 'His Majesty\'s Theatre',
    city: 'London, UK',
    section: 'Stalls',
    row: 'H',
    seatStart: '14',
    seatEnd: '15',
    quantity: 2,
    costPerTicket: 140.00,
    totalCost: 280.00,
    faceValue: 110.00,
    listPrice: 310.00,
    marketFloorPrice: 300.00,
    cardReference: 'Chase Ink #3310',
    specListing: false,
    status: 'Available',
    channels: { stubhub: true, vividseats: true, seatgeek: true, ticketmaster: true },
    barcodes: ['PHAN-HMT-ST-H14', 'PHAN-HMT-ST-H15'],
    lastRepricedAt: new Date().toISOString(),
  },
];

export async function initDatabase() {
  const count = await db.inventory.count();
  if (count === 0) {
    console.log('[Dexie] Initializing DB with seed inventory dataset...');
    const ids = await db.inventory.bulkAdd(INITIAL_INVENTORY_SEED as InventoryItem[], { allKeys: true });

    // Create matching initial mock orders for items marked as Sold
    const soldItems = await db.inventory.where('status').equals('Sold').toArray();

    const mockOrders: Omit<Order, 'id'>[] = [
      {
        inventoryId: soldItems[0]?.id || 2,
        orderNumber: 'ORD-88291',
        marketplace: 'StubHub',
        eventName: soldItems[0]?.eventName || 'Drake & 21 Savage - It\'s All A Blur Tour',
        eventDate: soldItems[0]?.eventDate || '2026-09-12T20:00:00.000Z',
        section: soldItems[0]?.section || '118',
        row: soldItems[0]?.row || '4',
        seats: '1-2',
        quantity: 2,
        salePricePerTicket: 620.00,
        totalGrossSale: 1240.00,
        commissionRate: 0.15,
        netPayout: 1054.00,
        orderDate: new Date(Date.now() - 3600000 * 5).toISOString(),
        fulfillmentStatus: 'Fulfilled',
        ingestedBarcodes: ['DRK-MSG-118-4-1', 'DRK-MSG-118-4-2'],
        deliveryDeadline: new Date(Date.now() + 86400000 * 2).toISOString(),
      },
      {
        inventoryId: soldItems[1]?.id || 9,
        orderNumber: 'ORD-91024',
        marketplace: 'Vivid Seats',
        eventName: soldItems[1]?.eventName || 'NBA Finals Game 7',
        eventDate: soldItems[1]?.eventDate || '2026-09-01T20:00:00.000Z',
        section: soldItems[1]?.section || 'Loge 1',
        row: soldItems[1]?.row || '10',
        seats: '3-4',
        quantity: 2,
        salePricePerTicket: 2450.00,
        totalGrossSale: 4900.00,
        commissionRate: 0.15,
        netPayout: 4165.00,
        orderDate: new Date(Date.now() - 3600000 * 2).toISOString(),
        fulfillmentStatus: 'Pending Barcode',
        ingestedBarcodes: [],
        deliveryDeadline: new Date(Date.now() + 3600000 * 12).toISOString(),
      },
      {
        inventoryId: soldItems[2]?.id || 11,
        orderNumber: 'ORD-77402',
        marketplace: 'SeatGeek',
        eventName: soldItems[2]?.eventName || 'New York Yankees vs Boston Red Sox',
        eventDate: soldItems[2]?.eventDate || '2026-09-15T19:05:00.000Z',
        section: soldItems[2]?.section || 'Main 214',
        row: soldItems[2]?.row || '3',
        seats: '1-4',
        quantity: 4,
        salePricePerTicket: 290.00,
        totalGrossSale: 1160.00,
        commissionRate: 0.15,
        netPayout: 986.00,
        orderDate: new Date(Date.now() - 3600000 * 18).toISOString(),
        fulfillmentStatus: 'Fulfilled',
        ingestedBarcodes: ['NYY-BOS-214-1', 'NYY-BOS-214-2', 'NYY-BOS-214-3', 'NYY-BOS-214-4'],
        deliveryDeadline: new Date(Date.now() + 86400000 * 5).toISOString(),
      },
      {
        inventoryId: soldItems[3]?.id || 19,
        orderNumber: 'ORD-65109',
        marketplace: 'Ticketmaster Resale',
        eventName: soldItems[3]?.eventName || 'Les Misérables - US Tour',
        eventDate: soldItems[3]?.eventDate || '2026-09-28T20:00:00.000Z',
        section: soldItems[3]?.section || 'Tier 1 Box',
        row: soldItems[3]?.row || 'A',
        seats: '1-4',
        quantity: 4,
        salePricePerTicket: 395.00,
        totalGrossSale: 1580.00,
        commissionRate: 0.15,
        netPayout: 1343.00,
        orderDate: new Date(Date.now() - 3600000 * 30).toISOString(),
        fulfillmentStatus: 'Pending Barcode',
        ingestedBarcodes: [],
        deliveryDeadline: new Date(Date.now() + 86400000 * 3).toISOString(),
      }
    ];

    await db.orders.bulkAdd(mockOrders as Order[]);

    // Seed default pricing rules
    await db.pricingRules.bulkAdd([
      {
        name: 'Market Floor Undercut',
        ruleType: 'UNDER_FLOOR',
        description: 'Auto-adjust price to $2.00 below market floor if current price exceeds floor.',
        isActive: true
      },
      {
        name: '48-Hour Event Time Decay',
        ruleType: 'TIME_DECAY',
        description: 'Reduce list price by 5% for unsold inventory when event starts in under 48 hours.',
        isActive: true
      },
      {
        name: 'Speculative Delivery Premium',
        ruleType: 'SPECULATIVE_MARKUP',
        description: 'Apply an 8% markup for speculative listings with delivery dates within 7 days.',
        isActive: true
      }
    ]);

    console.log('[Dexie] Database populated successfully.');
  }

  // Seed broker account
  const accountCount = await db.brokerAccount.count();
  if (accountCount === 0) {
    await db.brokerAccount.add({
      businessName: 'Demo Ticket Broker LLC',
      ownerName: 'John Broker',
      email: 'broker@example.com',
      phone: '(555) 123-4567',
      businessAddress: '123 Main Street',
      city: 'New York',
      state: 'NY',
      zipCode: '10001',
      taxId: '**-***1234',
      defaultCommissionRate: 0.15,
      minimumMarginPercent: 0.10,
      emailNotifications: true,
      smsNotifications: false,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    });
  }
}
